import {build} from 'esbuild';
import {readFile} from 'node:fs/promises';
import {resolve} from 'node:path';

// Shared by the development build and the generated per-plugin source snapshot.
export async function buildPlugin(base,entry){
  const result=await build({absWorkingDir:base,entryPoints:[entry],bundle:true,write:false,metafile:true,format:'cjs',platform:'browser',jsxFactory:'h',jsxFragment:'React.Fragment',target:'chrome130',minify:false,legalComments:'inline',define:{'process.env.NODE_ENV':'"production"'},loader:{'.css':'text','.svg':'text'}});
  const packages=new Set();
  for(const output of Object.values(result.metafile.outputs))for(const [name,value]of Object.entries(output.inputs)){
    const match=/^(.*node_modules\/(?:@[^/]+\/)?[^/]+)\//.exec(name.replaceAll('\\','/'));
    if(match&&value.bytesInOutput)packages.add(resolve(base,match[1]));
  }
  const notices=[];
  for(const directory of [...packages].sort()){
    const pkg=JSON.parse(await readFile(resolve(directory,'package.json'),'utf8'));
    let license;
    for(const name of ['LICENSE','LICENSE.md','LICENSE.txt','license','license.md'])try{license=await readFile(resolve(directory,name),'utf8');break;}catch(error){if(error.code!=='ENOENT')throw error;}
    if(!license)throw Error(`Missing third-party notice: ${pkg.name}@${pkg.version}`);
    notices.push(`${pkg.name}@${pkg.version} (${pkg.license})\n\n${license.trim()}`);
  }
  return {code:'// Generated by codlet-plugins/frontend/build.mjs\n'+result.outputFiles[0].text+'\n/*\n'+notices.join('\n\n---\n\n').replaceAll('*/','* /')+'\n*/\n',inputs:Object.keys(result.metafile.inputs).filter(path=>!path.replaceAll('\\','/').includes('node_modules/')).map(path=>resolve(base,path))};
}
